name: hCaptcha Solver
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
           
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/setup-python@v3
        with:
          python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
            
      - name: Show versions
        run: |
            python --version
            node -v
            
      - name: Install node dependencies
        run: |
            npm install
      
      - name: Run node script
        timeout-minutes: 2880
        run: |
            npm run start
